name: chat_bubbles
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.4.4
  dio: ^5.7.0
  easy_debounce: ^2.0.3
  fade_shimmer: ^2.2.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  overlay_support: ^2.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  ticker_text: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter_gen:
  output: lib/src/core/config/assets/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
